name = "pixel"
license = "MIT"
licenselink = ""
description = "Brutalist pixel art monospace theme for Hugo"
homepage = ""
tags = ["blog", "minimal", "monospace", "brutalist"]
features = ["", ""]
min_version = "0.120.0"

[author]
  name = "Eric Poirier"
