name = "pixel"
license = "MIT"
description = "Brutalist pixel art monospace theme for Hugo"
tags = ["blog", "minimal", "monospace", "brutalist"]
features = ["rss", "taxonomies", "custom-404"]
min_version = "0.120.0"

[author]
  name = "Eric Poirier"
